import Header from '@/components/header';
import Footer from '@/components/footer';

export const metadata = {
  title: '揪團滑雪頁面',
  description: 'Generated by create next app',
};

export default function ShopLayout({ children }) {
  return <>{children}</>;
}
